CREATE TABLE IF NOT EXISTS empleados (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
nombre VARCHAR(100) NOT NULL,
apellidos VARCHAR(100) NOT NULL,
fecha_nacimiento DATE NOT NULL,
fecha_incorporacion DATE NOT NULL,
salario DECIMAL(9,2) NOT NULL,
pais VARCHAR(100) NOT NULL,
rol VARCHAR(50) NOT NULL,
especialidad VARCHAR(100) DEFAULT NULL,
posicion VARCHAR(100) DEFAULT NULL,
dorsal INT DEFAULT NULL,
altura DOUBLE DEFAULT NULL,
peso DOUBLE DEFAULT NULL,
goles INT DEFAULT NULL,
partidos_jugados INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users (
    nombre_usuario VARCHAR(50) UNIQUE NOT NULL,
    contraseña VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL
);

